// <auto-generated />
namespace FirstBackEndProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTablesareadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTablesareadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202202122246298_New Tables are added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
